import Head from 'next/head';
import { Inter } from 'next/font/google';
import { fetcher } from '@/utils/fetcher';
import Article from '../components/Article';
import { endDate, tenDaysLess } from '@/utils/date';
import { HomeProps } from '@/utils/types';
import ImageOfTheDay from '@/components/ImageofTheDay';
import LastTenDaysImages from '@/components/LastTenDaysImages';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ imageOfTheDay, last10DaysImages }: HomeProps) {
  return (
    <>
      <Head>
        <title>Imágenes de la NASA</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col items-center justify-center p-2 text-white'>
        <Article>
          <ImageOfTheDay date={imageOfTheDay.date} url={imageOfTheDay.url} title={imageOfTheDay.title} />
        </Article>
        <Article>
          <LastTenDaysImages last10DaysImages={last10DaysImages} />
        </Article>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const imageOfTheDay = await fetcher();
    const last10DaysImages = await fetcher(`&start_date=${tenDaysLess}&end_date=${endDate}`)
    return {
      props: {
        imageOfTheDay,
        last10DaysImages,
      },
    };
  } catch (error) {
    console.error(error)
  }
}
